version: "3.8"

services:
  client:
    image: node:14
    restart: always
    user: root
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: bash -c "npm i && npm run dev"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker
    volumes:
      - "quizdata:/var/lib/postgresql/data"
      - "./quiz_db.sql:/docker-entrypoint-initdb.d/quiz_db.sql"
    ports:
      - "5432:5432"

volumes:
  quizdata:
